# Site settings
title:            Kemal
email:            dogruyolserdar@gmail.com
description:      'Lightning Fast, Super Simple web framework for Crystal. Inspired by Sinatra'
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "http://kemalcr.com" # the base hostname & protocol for your site
twitter_username: sdogruyol
github_username:  sdogruyol

# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        /blog/:year/:month/:day/:title/

collections:
  docs:
    output: true

nav_bars:
  - title: "Documentation"
    url: "/docs/getting_started"
  - title: "Community"
    url: "/community"
  - title: "Github"
    url: "https://github.com/sdogruyol/kemal"
  - title: "Blog"
    url: "/blog"

examples:
  - title: "How to connect to Database"
    url: "https://github.com/sdogruyol/kemal-pg-sample"
